### ISSUE TITLE
Error trying to use commands that query or cancel single orders.

### ISSUE THREAD

**Issue by kenchvz** [Binance-docs/binance-futures-connector-python#3] opened 2021-12-17 20:22 UTC
When I try and use the commands query_order and cancel_order, I keep getting the same error that the specified orders do not exist. 

For example I would open a stop loss order on DOGEUSDT with a specified origClientOrderId and this order would appear as so when i print the order.
{'orderId': 123929928, 'symbol': 'DOGEUSDT', 'status': 'NEW', 'clientOrderId': '12345678', 'price': '0', 'avgPrice': '0', 'origQty': '150', 'executedQty': '0', 'cumQuote': '0', 'timeInForce': 'GTC', 'type': 'STOP_MARKET', 'reduceOnly': True, 'closePosition': False, 'side': 'SELL', 'positionSide': 'LONG', 'stopPrice': '0.160000', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'STOP_MARKET', 'time': 1639763154202, 'updateTime': 1639763154202}

But if I use the single command with query_order and the specified id, I keep getting the error saying it does not exist. I have tried with using either orderId or origClientOrderId and by passing them as both a str and int and none seem to work

this is the command I am using:
futures_client.get_order(
    symbol =    'DOGEUSDT',
    origClientOrderId = '12345678'
)

Of course I have tried using OrderId also and even retrieving the specific ID's from get_orders and still I get the error that those don't exist. Also it seems this error is persistent with commands that seek a specific order, because I get the same error when I try the command cancel_order with a specified ID.

**Comment by hilmiazizi** [comment] 2022-01-10 17:53
hello, do you found any solution for this? having the same issue, this giving me headache for last 3 days

**Comment by ronekarleone** [comment] 2022-01-15 10:34
Hello, you can use solutuon like this: https://github.com/Binance-docs/binance-futures-connector-python/issues/8#issuecomment-1013658618

**Comment by 2pd** [comment] 2022-02-11 07:40
Please try again with latest release. thanks.

**Comment by ctin** [comment] 2022-02-20 16:04
I created the duplicate of this issue just ~~because I am not that smart~~ to link the [pull request](https://github.com/Binance-docs/binance-futures-connector-python/pull/13) with a fix to it.

**Closed** 2022-03-04 07:06 UTC
